import 'package:flutter/material.dart';
import 'package:weather_app/core/constants/mycolors.dart';
import 'package:weather_app/core/constants/shortMediaQuery.dart';

class SearchPage extends StatefulWidget {
  const SearchPage({Key? key}) : super(key: key);

  @override
  State<SearchPage> createState() => _SearchPageState();
}

class _SearchPageState extends State<SearchPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
       body: Container(
         height: m_h(context),
         width: m_w(context),
         decoration: const BoxDecoration(
           gradient: LinearGradient(
               colors: [
                 MyColor.C_2A274F,
                 MyColor.C_432A79,
                 MyColor.C_2A274F,
               ]
           ),
         ),
         child: Column(
           children: [
             SizedBox(height: 80,),
             Container(
               height: 50,
               width: 380,
               decoration: BoxDecoration(
                 borderRadius: BorderRadius.circular(30),
                 color:  MyColor.C_1C1B33,
                 border: Border.all(color: MyColor.C_1C1B33,width: 1)
               ),
              child: Padding(
                padding: const EdgeInsets.only(left: 15),
                child: Row(
                  children: [
                    Icon(Icons.search_outlined, color: Colors.white,),
                    TextFormField(
                        
                    )
                  ],
                ),
              ),
             ),
             
             Container(
               height: 40,
               width: double.infinity,
               child: ListView.builder(
                   itemCount: countries.length,
                   itemBuilder: (context, index) {
                 return Container(
                   child: Text(countries[index]),
                 );
               }),
             )
           ],

         ),
       ),
    );
  }
}


List countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'the bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bonaire',
  'Bosnia',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British',
  'Bulgaria',
  'Burkina',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'the cayman islands',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'the comoros',
  'Congo',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Ecuador',
  'Egypt',
  'Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'southe korea',
  'Kuwait',
  "north korea",
  'Kyrgyzstan',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestinian',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Qatar',
  'Romania',
  'Rwanda',
  'Samoa',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'Spain',
  'Sudan',
  'Suriname',
  'Sudan',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'UAE',
  'united kingdom',
  'USA',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];